<?php

/**
 * Référentiel de notions — Primaire 2 (PFEQ, Québec).
 * Clé = matière (Subjects.name). Catégorie => skill + notions.
 */
return [
    'Français' => [
        'Lecture' => [
            'skill' => 'Lecture et compréhension',
            'notions' => [
                'Reconnaître les lettres et leurs sons',
                'Lire des mots fréquents',
                'Lire des phrases',
                'Lire de courts textes',
                'Comprendre un texte',
                'Trouver l\'idée principale',
                'Répondre à des questions sur un texte',
                'Identifier les personnages',
                'Identifier le lieu',
                'Identifier le temps',
                'Remettre une histoire en ordre',
                'Faire des prédictions',
                'Trouver des indices dans un texte',
                'Enrichir son vocabulaire',
                'Utiliser le contexte pour comprendre un mot',
            ],
        ],
        'Écriture' => [
            'skill' => 'Écriture',
            'notions' => [
                'Écrire des phrases complètes',
                'Écrire un court texte',
                'Raconter une histoire',
                'Décrire une personne',
                'Décrire un animal',
                'Décrire un objet',
                'Décrire un lieu',
                'Écrire une liste',
                'Écrire une invitation',
                'Copier correctement',
                'Réviser un texte',
                'Corriger les erreurs simples',
            ],
        ],
        'Grammaire' => [
            'skill' => 'Grammaire',
            'notions' => [
                'La phrase',
                'La majuscule',
                'Le point',
                'Le point d\'interrogation',
                'Le point d\'exclamation',
                'Le nom commun',
                'Le nom propre',
                'Le déterminant',
                'L\'adjectif',
                'Le verbe',
                'Le pronom (je, tu, il, elle, nous, vous, ils, elles)',
                'Le groupe du nom (GN)',
                'Le sujet',
                'Le prédicat (introduction)',
                'Les phrases affirmatives',
                'Les phrases négatives',
                'Les phrases interrogatives',
                'Les phrases exclamatives',
            ],
        ],
        'Conjugaison' => [
            'skill' => 'Grammaire',
            'notions' => [
                'Verbes du 1er groupe (-er)',
                'Être',
                'Avoir',
                'Aller',
                'Faire',
                'Dire',
                'Présent de l\'indicatif',
                'Futur proche',
                'Passé composé (reconnaissance simple)',
            ],
        ],
        'Orthographe' => [
            'skill' => 'Orthographe',
            'notions' => [
                'Mots fréquents',
                'Sons complexes',
                'Accords simples',
                'Accord déterminant-nom',
                'Accord nom-adjectif',
                'Accord sujet-verbe (simple)',
                'Homophones simples',
                'Apostrophe',
                'Traits d\'union (bases)',
            ],
        ],
    ],

    'Mathématiques' => [
        'Les nombres' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Compter jusqu\'à 1000',
                'Lire les nombres',
                'Écrire les nombres',
                'Comparer les nombres',
                'Ranger les nombres',
                'Valeur de position — unités',
                'Valeur de position — dizaines',
                'Valeur de position — centaines',
                'Décomposer un nombre',
                'Composer un nombre',
                'Nombres pairs',
                'Nombres impairs',
                'Suites numériques',
                'Compter par 2',
                'Compter par 5',
                'Compter par 10',
                'Compter par 25',
                'Compter par 100',
            ],
        ],
        'Addition' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Additions sans retenue',
                'Additions avec retenue',
                'Calcul mental — addition',
                'Estimation — addition',
                'Résolution de problèmes — addition',
            ],
        ],
        'Soustraction' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Soustractions sans emprunt',
                'Soustractions avec emprunt',
                'Calcul mental — soustraction',
                'Résolution de problèmes — soustraction',
            ],
        ],
        'Multiplication (introduction)' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Groupements égaux',
                'Répétition d\'additions',
                'Tables de 2',
                'Tables de 5',
                'Tables de 10',
            ],
        ],
        'Division (initiation)' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Partage égal',
                'Regroupement',
            ],
        ],
        'Géométrie' => [
            'skill' => 'Géométrie',
            'notions' => [
                'Cercle',
                'Carré',
                'Rectangle',
                'Triangle',
                'Losange',
                'Ovale',
                'Pentagone (initiation)',
                'Hexagone (initiation)',
                'Cube',
                'Sphère',
                'Cylindre',
                'Cône',
                'Prisme',
                'Faces',
                'Sommets',
                'Arêtes',
            ],
        ],
        'Mesure' => [
            'skill' => 'Mesures',
            'notions' => [
                'Longueur',
                'Masse',
                'Capacité',
                'Temps',
                'Heure',
                'Demi-heure',
                'Quart d\'heure (initiation)',
                'Calendrier',
                'Jours',
                'Mois',
                'Saisons',
                'Température',
                'Monnaie canadienne',
            ],
        ],
        'Statistique' => [
            'skill' => 'Logique',
            'notions' => [
                'Lire un tableau',
                'Construire un tableau',
                'Diagramme à pictogrammes',
                'Diagramme à bandes',
                'Collecte de données',
            ],
        ],
        'Probabilité' => [
            'skill' => 'Logique',
            'notions' => [
                'Certain',
                'Possible',
                'Impossible',
            ],
        ],
    ],

    'Sciences' => [
        'Les êtres vivants' => [
            'skill' => 'Univers vivant',
            'notions' => [
                'Animaux',
                'Plantes',
                'Besoins des êtres vivants',
                'Croissance',
                'Habitat',
                'Adaptation',
                'Chaîne alimentaire (simple)',
            ],
        ],
        'Le corps humain' => [
            'skill' => 'Univers vivant',
            'notions' => [
                'Les cinq sens',
                'Parties du corps',
                'Hygiène',
                'Alimentation',
                'Activité physique',
            ],
        ],
        'Matière' => [
            'skill' => 'Univers matériel',
            'notions' => [
                'Solide',
                'Liquide',
                'Gaz (introduction)',
                'Flotter',
                'Couler',
                'Mélanges simples',
            ],
        ],
        'Énergie' => [
            'skill' => 'Univers matériel',
            'notions' => [
                'Lumière',
                'Chaleur',
                'Son',
            ],
        ],
        'Terre et espace' => [
            'skill' => 'Terre et espace',
            'notions' => [
                'Jour',
                'Nuit',
                'Soleil',
                'Lune',
                'Saisons',
                'Météo',
                'Cycle de l\'eau (simple)',
            ],
        ],
        'Technologie' => [
            'skill' => 'Expérimentation',
            'notions' => [
                'Objets du quotidien',
                'Matériaux',
                'Utilité des objets',
                'Construction simple',
            ],
        ],
    ],

    'Univers social' => [
        'Géographie' => [
            'notions' => [
                'Ma maison',
                'Mon école',
                'Mon quartier',
                'Ma ville',
                'Le Québec',
                'Carte simple',
                'Points cardinaux',
                'Repères',
            ],
        ],
        'Histoire' => [
            'notions' => [
                'Ma famille',
                'Changements dans le temps',
                'Avant / aujourd\'hui',
                'Traditions',
                'Fêtes',
            ],
        ],
        'Citoyenneté' => [
            'notions' => [
                'Respect',
                'Politesse',
                'Règles de vie',
                'Partage',
                'Coopération',
                'Responsabilités',
            ],
        ],
    ],

    'Anglais' => [
        'Communication' => [
            'notions' => [
                'Se présenter',
                'Dire son âge',
                'Dire son nom',
                'Saluer',
                'Remercier',
                'Poser des questions simples',
            ],
        ],
        'Vocabulaire' => [
            'notions' => [
                'Couleurs',
                'Nombres',
                'Alphabet',
                'Animaux',
                'Famille',
                'École',
                'Maison',
                'Nourriture',
                'Vêtements',
                'Parties du corps',
                'Jouets',
                'Émotions',
                'Météo',
                'Jours de la semaine',
                'Mois',
                'Saisons',
            ],
        ],
        'Grammaire' => [
            'notions' => [
                'I am',
                'You are',
                'He is',
                'She is',
                'It is',
                'Have / Has',
                'Articles (a, an, the)',
                'Pronoms personnels',
                'Pluriels simples',
            ],
        ],
    ],

    'Éthique et culture religieuse' => [
        'Culture et citoyenneté québécoise' => [
            'notions' => [
                'Respect des autres',
                'Amitié',
                'Émotions',
                'Différences',
                'Inclusion',
                'Entraide',
                'Résolution de conflits',
                'Responsabilité',
                'Vie en groupe',
            ],
        ],
    ],

    'Éducation physique' => [
        'Activités physiques' => [
            'skill' => 'Activité physique',
            'notions' => [
                'Courir',
                'Marcher',
                'Sauter',
                'Lancer',
                'Attraper',
                'Équilibre',
                'Coordination',
                'Jeux coopératifs',
                'Jeux d\'équipe',
                'Sécurité',
                'Habitudes de vie',
            ],
        ],
    ],
];
