<?php

/**
 * Faits scientifiques quotidiens pour la page d'accueil élève.
 * Rotation déterministe par jour de l'année (1–366).
 */
return [
    [
        'category' => 'Espace',
        'emoji' => '🚀',
        'color' => '#6366f1',
        'title' => 'La Lune s\'éloigne',
        'fact' => 'Chaque année, la Lune s\'éloigne de la Terre d\'environ 3,8 cm — à peu près la vitesse à laquelle poussent tes ongles !',
        'question' => 'Pourquoi voit-on toujours la même face de la Lune depuis la Terre ?',
    ],
    [
        'category' => 'Animaux',
        'emoji' => '🐙',
        'color' => '#8b5cf6',
        'title' => 'Le cœur des pieuvres',
        'fact' => 'Une pieuvre a trois cœurs et son sang est bleu à cause du cuivre qu\'il contient, au lieu du fer comme chez les humains.',
        'question' => 'Combien de bras possède une pieuvre ?',
    ],
    [
        'category' => 'Corps humain',
        'emoji' => '🧠',
        'color' => '#ec4899',
        'title' => 'Ton cerveau super-puissant',
        'fact' => 'Ton cerveau envoie des messages à la vitesse de 400 km/h — plus rapide qu\'une voiture sur l\'autoroute !',
        'question' => 'Quel organe consomme le plus d\'énergie dans ton corps ?',
    ],
    [
        'category' => 'Plantes',
        'emoji' => '🌿',
        'color' => '#22c55e',
        'title' => 'Les arbres communiquent',
        'fact' => 'Les arbres peuvent s\'avertir les uns les autres du danger grâce à un réseau de racines et de champignons souterrains.',
        'question' => 'Comment les plantes fabriquent-elles leur nourriture ?',
    ],
    [
        'category' => 'Océan',
        'emoji' => '🌊',
        'color' => '#06b6d4',
        'title' => 'Mystères des abysses',
        'fact' => 'Plus de 80 % de l\'océan reste inexploré — nous en savons plus sur la surface de Mars que sur le fond des mers !',
        'question' => 'Quel est le plus grand océan du monde ?',
    ],
    [
        'category' => 'Physique',
        'emoji' => '⚡',
        'color' => '#f59e0b',
        'title' => 'La foudre ultra-rapide',
        'fact' => 'Un éclair peut chauffer l\'air autour de lui à 30 000 °C — cinq fois plus chaud que la surface du Soleil !',
        'question' => 'Le son ou la lumière arrive-t-il en premier pendant un orage ?',
    ],
    [
        'category' => 'Dinosaures',
        'emoji' => '🦕',
        'color' => '#84cc16',
        'title' => 'Des géants colorés ?',
        'fact' => 'Les scientifiques pensent que certains dinosaures avaient des plumes colorées, un peu comme des oiseaux géants !',
        'question' => 'Qu\'est-ce qui a causé la disparition des dinosaures il y a 66 millions d\'années ?',
    ],
    [
        'category' => 'Volcans',
        'emoji' => '🌋',
        'color' => '#ef4444',
        'title' => 'Terre qui respire',
        'fact' => 'Il y a environ 1 500 volcans actifs sur Terre. Le plus grand, Mauna Loa à Hawaï, mesure plus de 9 km de haut depuis le fond de l\'océan.',
        'question' => 'Qu\'est-ce qui sort d\'un volcan en éruption ?',
    ],
    [
        'category' => 'Insectes',
        'emoji' => '🐝',
        'color' => '#eab308',
        'title' => 'Danse des abeilles',
        'fact' => 'Les abeilles dansent en forme de « 8 » pour indiquer à leurs amies où trouver les meilleures fleurs — c\'est leur propre GPS !',
        'question' => 'Pourquoi les abeilles sont-elles importantes pour les fleurs ?',
    ],
    [
        'category' => 'Climat',
        'emoji' => '🌈',
        'color' => '#a855f7',
        'title' => 'Arc-en-ciel magique',
        'fact' => 'Un arc-en-ciel est en réalité un cercle complet — depuis un avion, tu peux parfois voir le cercle entier !',
        'question' => 'Quelles couleurs composent un arc-en-ciel ?',
    ],
    [
        'category' => 'Matériaux',
        'emoji' => '💎',
        'color' => '#14b8a6',
        'title' => 'Diamant = carbone',
        'fact' => 'Le diamant et le graphite (mine de crayon) sont faits du même élément : le carbone — seule leur structure change !',
        'question' => 'Quel est l\'élément chimique le plus abondant dans l\'univers ?',
    ],
    [
        'category' => 'Son',
        'emoji' => '🎵',
        'color' => '#3b82f6',
        'title' => 'Silence dans l\'espace',
        'fact' => 'Dans l\'espace, personne ne t\'entend crier — le son a besoin d\'air ou d\'eau pour voyager, et l\'espace est presque vide !',
        'question' => 'Comment entend-on les choses autour de nous ?',
    ],
    [
        'category' => 'Microbes',
        'emoji' => '🔬',
        'color' => '#10b981',
        'title' => 'Monde invisible',
        'fact' => 'Sur tes mains, il y a plus de bactéries que d\'humains sur toute la planète — mais la plupart sont inoffensives ou utiles !',
        'question' => 'Pourquoi faut-il se laver les mains avant de manger ?',
    ],
    [
        'category' => 'Énergie',
        'emoji' => '☀️',
        'color' => '#f97316',
        'title' => 'Le Soleil généreux',
        'fact' => 'En une seconde, le Soleil produit assez d\'énergie pour alimenter la Terre entière pendant 500 000 ans !',
        'question' => 'D\'où vient l\'énergie des plantes vertes ?',
    ],
    [
        'category' => 'Glace',
        'emoji' => '🧊',
        'color' => '#38bdf8',
        'title' => 'Glace qui flotte',
        'fact' => 'La glace flotte sur l\'eau parce qu\'elle est moins dense — sans ça, les lacs gèleraient par le bas et la vie aquatique mourrait !',
        'question' => 'À quelle température l\'eau gèle-t-elle ?',
    ],
];
