<?php

/**
 * Référentiel de notions — programme québécois (PFEQ, primaire).
 * Clé = nom de la matière (Subjects.name). Catégorie => liste de titres de notions.
 */
return [
    'Français' => [
        'Lecture — Compréhension de textes' => [
            'skill' => 'Lecture et compréhension',
            'notions' => [
                'Idée principale et idées secondaires',
                'Faire des inférences',
                'Repérer les informations importantes',
                'Résumer un texte',
                'Identifier le type de texte',
                'Intention de l\'auteur',
                'Point de vue',
            ],
        ],
        'Lecture — Vocabulaire' => [
            'skill' => 'Vocabulaire',
            'notions' => [
                'Expressions figurées',
                'Synonymes',
                'Antonymes',
                'Champs lexicaux',
            ],
        ],
        'Écriture' => [
            'skill' => 'Écriture',
            'notions' => [
                'Texte narratif',
                'Texte descriptif',
                'Texte explicatif',
                'Texte informatif',
                'Texte d\'opinion',
                'Lettre',
                'Dialogue',
                'Planification',
                'Révision',
                'Correction',
                'Enrichissement des phrases',
                'Cohérence du texte',
                'Paragraphes',
            ],
        ],
        'Grammaire' => [
            'skill' => 'Grammaire',
            'notions' => [
                'Groupe du nom (GN)',
                'Déterminants',
                'Noms',
                'Adjectifs',
                'Pronoms',
                'Verbes',
                'Adverbes',
                'Prépositions',
                'Conjonctions',
                'Sujet',
                'Prédicat',
                'Complément de phrase',
                'Complément direct (CD)',
                'Complément indirect (CI)',
                'Attribut du sujet',
                'Accord du verbe',
                'Accord dans le GN',
                'Accord du participe passé (notions de base)',
            ],
        ],
        'Conjugaison' => [
            'skill' => 'Grammaire',
            'notions' => [
                'Présent',
                'Imparfait',
                'Futur simple',
                'Passé composé',
                'Conditionnel présent',
                'Impératif',
                'Infinitif',
                'Participes',
                'Groupes de verbes',
            ],
        ],
        'Orthographe' => [
            'skill' => 'Orthographe',
            'notions' => [
                'Homophones',
                'Accords',
                'Majuscules',
                'Ponctuation',
                'Mots fréquents',
                'Préfixes',
                'Suffixes',
                'Familles de mots',
            ],
        ],
    ],

    'Mathématiques' => [
        'Nombres' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Valeur de position',
                'Nombres naturels',
                'Comparaison',
                'Ordre croissant et décroissant',
                'Arrondissement',
                'Décomposition',
                'Multiples',
                'Diviseurs',
                'Critères de divisibilité',
                'Nombres premiers',
                'Fractions',
                'Fractions équivalentes',
                'Comparaison de fractions',
                'Décimaux',
                'Conversion fractions ↔ décimaux',
                'Pourcentages (initiation)',
            ],
        ],
        'Opérations' => [
            'skill' => 'Arithmétique',
            'notions' => [
                'Addition',
                'Soustraction',
                'Multiplication',
                'Division',
                'Priorité des opérations',
                'Estimation',
                'Calcul mental',
                'Résolution de problèmes',
            ],
        ],
        'Géométrie' => [
            'skill' => 'Géométrie',
            'notions' => [
                'Droites',
                'Segments',
                'Angles',
                'Triangles',
                'Quadrilatères',
                'Polygones',
                'Cercle',
                'Symétrie',
                'Rotation',
                'Translation',
                'Solides',
                'Prismes',
                'Cylindres',
                'Cubes',
                'Pyramides',
            ],
        ],
        'Mesure' => [
            'skill' => 'Mesures',
            'notions' => [
                'Longueur',
                'Masse',
                'Capacité',
                'Temps',
                'Température',
                'Aire',
                'Périmètre',
                'Volume (introduction)',
                'Conversion d\'unités',
            ],
        ],
        'Statistique' => [
            'skill' => 'Logique',
            'notions' => [
                'Tableaux',
                'Diagrammes',
                'Graphiques',
                'Moyenne (initiation)',
                'Mode',
                'Collecte de données',
            ],
        ],
        'Probabilité' => [
            'skill' => 'Logique',
            'notions' => [
                'Événements certains',
                'Possibles',
                'Impossibles',
                'Comparaison des probabilités',
            ],
        ],
    ],

    'Sciences' => [
        'Univers matériel' => [
            'skill' => 'Univers matériel',
            'notions' => [
                'États de la matière',
                'Changements d\'état',
                'Mélanges',
                'Solutions',
                'Propriétés des matériaux',
                'Conducteurs et isolants',
                'Forces',
                'Machines simples',
                'Énergie',
                'Électricité (base)',
            ],
        ],
        'Univers vivant' => [
            'skill' => 'Univers vivant',
            'notions' => [
                'Cellules (notion simple)',
                'Êtres vivants',
                'Besoins des êtres vivants',
                'Chaînes alimentaires',
                'Écosystèmes',
                'Adaptations',
                'Reproduction',
                'Croissance',
                'Biodiversité',
            ],
        ],
        'Terre et espace' => [
            'skill' => 'Terre et espace',
            'notions' => [
                'Système solaire',
                'Planètes',
                'Rotation',
                'Révolution',
                'Saisons',
                'Jour et nuit',
                'Phases de la Lune',
                'Météo',
                'Climat',
                'Cycle de l\'eau',
            ],
        ],
        'Technologie' => [
            'skill' => 'Expérimentation',
            'notions' => [
                'Démarche de conception',
                'Objets techniques',
                'Matériaux',
                'Mécanismes simples',
                'Schémas',
                'Plans',
            ],
        ],
    ],

    'Géographie' => [
        'Géographie du Québec' => [
            'skill' => 'Territoires',
            'notions' => [
                'Territoire québécois',
                'Régions du Québec',
                'Population',
                'Ressources naturelles',
                'Climat',
                'Cartes',
                'Orientation',
                'Latitude',
                'Longitude',
                'Urbanisation',
            ],
        ],
    ],

    'Histoire' => [
        'Histoire du Québec et du Canada' => [
            'skill' => 'Temps historique',
            'notions' => [
                'Premières Nations',
                'Nouvelle-France',
                'Colonisation',
                'Régime français',
                'Régime britannique',
                'Développement du Québec',
                'Événements historiques importants',
                'Personnages historiques',
            ],
        ],
    ],

    'Univers social' => [
        'Éducation à la citoyenneté' => [
            'notions' => [
                'Droits',
                'Responsabilités',
                'Démocratie',
                'Diversité culturelle',
                'Vie en société',
                'Coopération',
                'Respect',
            ],
        ],
    ],

    'Anglais' => [
        'Communication' => [
            'notions' => [
                'Se présenter',
                'Décrire une personne',
                'Décrire un lieu',
                'Décrire des objets',
                'Poser des questions',
                'Donner son opinion',
                'Exprimer ses goûts',
                'Donner des instructions',
            ],
        ],
        'Vocabulaire' => [
            'notions' => [
                'Famille',
                'École',
                'Animaux',
                'Nourriture',
                'Sports',
                'Maison',
                'Ville',
                'Voyages',
                'Métiers',
                'Vêtements',
                'Corps humain',
                'Météo',
                'Émotions',
            ],
        ],
        'Grammaire' => [
            'notions' => [
                'Present Simple',
                'Present Continuous',
                'Past Simple (initiation)',
                'Future (going to)',
                'Pronoms',
                'Articles',
                'Prépositions',
                'Adjectifs',
                'Comparatifs',
                'Superlatifs',
            ],
        ],
    ],

    'Éthique et culture religieuse' => [
        'Valeurs et vivre-ensemble' => [
            'notions' => [
                'Respect',
                'Tolérance',
                'Diversité',
                'Inclusion',
                'Identité',
                'Culture',
                'Valeurs',
                'Dialogue',
                'Coopération',
                'Résolution de conflits',
                'Médias',
                'Citoyenneté numérique',
            ],
        ],
    ],

    'Éducation physique' => [
        'Activités physiques' => [
            'skill' => 'Motricité',
            'notions' => [
                'Course',
                'Saut',
                'Lancer',
                'Jeux collectifs',
                'Coordination',
                'Endurance',
                'Force',
                'Souplesse',
                'Esprit sportif',
                'Santé',
                'Sécurité',
                'Travail d\'équipe',
            ],
        ],
    ],
];
